### ISSUE TITLE
google drive link not working

### ISSUE THREAD

**Issue by consciouscomputingengineering** [priya-dwivedi/aerial_pedestrian_detection#1]

**Comment by consciouscomputingengineering** [comment]
Also,   import keras_resnet
ModuleNotFoundError: No module named 'keras_resnet'

**Comment by shedon85** [comment]
it has a link in this article: 
https://towardsdatascience.com/pedestrian-detection-in-aerial-images-using-retinanet-9053e8a72c6
link to the drive:
https://drive.google.com/drive/u/0/folders/1QpE_iRDq1hUzYNBXSBSnmfe6SgTYE3J4

**Comment by priya-dwivedi** [comment]
Please check again:
https://drive.google.com/drive/u/1/folders/1QpE_iRDq1hUzYNBXSBSnmfe6SgTYE3J4

**Comment by askari12** [comment]
The link works but it does not allow me to download the model. Could you change the settings so I can download the model ?

**Comment by askari12** [comment]
> Access to doc-0k-8k-docs.googleusercontent.com was deniedYou don't have authorization to view this page.
> HTTP ERROR 403


This is the error I get.

**Comment by shedon85** [comment]
Sorry about that.
Who you are? Why are you trying to access our drive?

Ido Yahalomi
Founder & Business Development, High Lander
+972-507502207
www.highlander.io

**Comment by askari12** [comment]
I'm a student in Bilkent University, Turkey and was looking at your image analysis model for my machine learning term project. Was trying to follow along the tutorial on the article in medium.

Would be a huge help for me to understand how the model works if I can test it. Was trying to download the weights.

**Comment by shedon85** [comment]
I'm very sorry, but the model is our IP.
I can't share it with you.

Ido Yahalomi
Founder & Business Development, High Lander
+972-507502207
www.highlander.io

**Comment by askari12** [comment]
Okay, All the best !

**Comment by priya-dwivedi** [comment]
@askari12 - The link - https://drive.google.com/drive/folders/1QpE_iRDq1hUzYNBXSBSnmfe6SgTYE3J4?usp=sharing
should work. This is a link tied to my google drive and has open access

@shedon85 - There is some confusion. We are not trying to access your drive
