### ISSUE TITLE
Keras import error

### ISSUE THREAD

**Issue by shaheryar1** [priya-dwivedi/aerial_pedestrian_detection#16]
I have followed all the steps for running the repository , but when I execute keras_retinanet/bin/train.py  following error occurs. 

  _File "keras_retinanet/bin/train.py", line 24, in <module>
    import keras
ImportError: No module named keras_

Although keras==2.3.1 is installed

**Comment by cmphil13** [comment]
> I have followed all the steps for running the repository , but when I execute keras_retinanet/bin/train.py following error occurs.
> 
> _File "keras_retinanet/bin/train.py", line 24, in import keras ImportError: No module named keras_
> 
> Although keras==2.3.1 is installed

Hello  @shaheryar1, I am experiencing the same issue. How did you solve this problem?
