### ISSUE TITLE
Training Images link does not work! 

### ISSUE THREAD

**Issue by aprentis** [priya-dwivedi/aerial_pedestrian_detection#4]

**Comment by shedon85** [comment]
it has a link in this article: 
https://towardsdatascience.com/pedestrian-detection-in-aerial-images-using-retinanet-9053e8a72c6
link to the drive:
https://drive.google.com/drive/u/0/folders/1QpE_iRDq1hUzYNBXSBSnmfe6SgTYE3J4

**Comment by priya-dwivedi** [comment]
Please check again
https://drive.google.com/drive/u/1/folders/1QpE_iRDq1hUzYNBXSBSnmfe6SgTYE3J4
