### ISSUE TITLE
Trained model weight file

### ISSUE THREAD

**Issue by shubham9436** [priya-dwivedi/aerial_pedestrian_detection#8]
Hi Priya...
Could you please upload the weight file?
I followed the steps but could not obtain the higher accuracy.
Thanks

**Comment by xuxiyang1993** [comment]
I have the same problem. The mAP is lowering after each epoch, from 0.16 to 0.12

**Comment by priya-dwivedi** [comment]
Trained model is uploaded to 
https://drive.google.com/drive/u/1/folders/1l6skiSrhTfbqTvfHf_I3pneJtQ8O7NQa
